Development PR
HighOnDevsinc/WeatherManClass pull request #1
Opened 2024-07-09 22:08 UTC by HighOnDevsinc

Done with my work.

2024-07-10 01:06 UTC, mehmooddevsinc requested changes
Resolve requested changes. Also move classes to separate modules. Modules names must be in snake_case not CamelCase. Doc string are inside block(class, function). Do read about doc strings and fix usage of that.

2024-07-10 01:06 UTC, mehmooddevsinc commented on Weather.py
> +        self.WindDirDegrees = wind_dir_degrees
only use required data. No need to read whole record. Also use snake_case for variables. e.g
self.max_temperature_c = max_temp_c

2024-07-10 01:06 UTC, mehmooddevsinc commented on Weather.py
> +        return month_name[month_number - 1]
Use static dict instead of method. Also search reason for that.

2024-07-10 01:06 UTC, mehmooddevsinc commented on Weather.py
> +        return s.join(date)
is this method essential?

2024-07-10 01:06 UTC, mehmooddevsinc commented on Weather.py
> +                with open(self.arguments[2] + "/" + file) as file_object:
use string interpolation instead

2024-07-10 01:06 UTC, mehmooddevsinc commented on Weather.py
> +                max_temp = int(extracted_tuple.MaxTemperatureC)
use float instead of int for scalability purpose

2024-07-10 01:06 UTC, mehmooddevsinc commented on Weather.py
> +            ]
there should be comma after max_humid_day. Preferable style is below
result = [
      max_temp, max_temp_day,
      min_temp, min_temp_day,
      max_humid, max_humid_day,
]

2024-07-10 01:06 UTC, mehmooddevsinc commented on Weather.py
> +            ]
fix it same as mentioned above. Also use float instead of int. but it should be precise up to 2 decimal places.

2024-07-10 01:06 UTC, mehmooddevsinc commented on Weather.py
> +            print("Average Humidity:", result[2], "%")
use string interpolation

2024-07-10 01:06 UTC, mehmooddevsinc commented on Weather.py
> +            print("Humid:", result[4], r"% on", result[5])
use string interpolation

2024-07-10 01:06 UTC, mehmooddevsinc commented on Weather.py
> +    def monthly_chart_temperature_and_humidity(self):
Look at the requirement again. You are miss-interpreting chart requirement. Do ask me if you still have confussion.

2024-07-31 15:08 UTC, HighOnDevsinc commented on Weather.py
> +        return s.join(date)
Yes it is essential as it is called in a function multiple times

2024-08-01 18:33 UTC, merged